version: '3'

services:
  app:
    build: './project'
    container_name: 'social-network_app'
    command: daphne config.asgi:application -b 0.0.0.0 -p 8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  celery:
    build:
      context: './project'
      dockerfile: './Dockerfile.celery'
    container_name: 'social-network_celery'
    command: celery -A config.celery worker -l INFO
    env_file:
      - ./.env.dev
    depends_on:
      - app
      - db
      - redis

  db:
    image: postgres:13-alpine
    container_name: 'social-network_db'
    volumes:
      - pg-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=database
  
  redis:
    image: redis:6-alpine
    container_name: 'social-network_redis'

volumes:
  pg-data:
