version: '3'

services:
  app:
    build: './project'
    container_name: 'social-network_app'
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  messages:
    build: './messages'
    container_name: 'social-network_messages'
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - 8001:8001
    env_file:
      - ./.env.dev
    depends_on:
      - app
      - db

  db:
    image: postgres:13-alpine
    container_name: 'social-network_db'
    volumes:
      - pg-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=database

volumes:
  pg-data:
