version: '3'

services:
  web:
    build: 
      context: './project'
      dockerfile: Dockerfile.prod
    container_name: 'web'
    command: gunicorn config.wsgi:application -c config/gunicorn.conf.py --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    expose:
      - 8000
    volumes:
      - static_volume:/app/web/static
      - media_volume:/app/web/media
    depends_on:
      - db

  messages:
    build: './messages'
    container_name: 'social-network_messages'
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - 8001:8001
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/app/web/static
      - media_volume:/app/web/media
    depends_on:
      - web
      - messages

volumes:
  pg-data:
  static_volume:
  media_volume: