version: '3'

services:
  web:
    build: 
      context: './project'
      dockerfile: Dockerfile.prod
    container_name: 'web'
    command: daphne config.asgi:application -b 0.0.0.0 -p 8000
    env_file:
      - ./.env.prod
    expose:
      - 8000
    volumes:
      - static_volume:/app/web/static
      - media_volume:/app/web/media
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  redis:
    image: redis:6-alpine
    container_name: 'social-network_redis'

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/app/web/static
      - media_volume:/app/web/media
    depends_on:
      - web

volumes:
  pg-data:
  static_volume:
  media_volume: