# Generated by Django 3.2.8 on 2021-10-23 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_accounts_customuser_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
