# Generated by Django 3.2.8 on 2021-11-09 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0004_auto_20211109_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='_accounts_customuser_friend_requests_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'accounts'), ('model', 'customuser')), models.Q(('app_label', 'chat'), ('model', 'message')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
