# Generated by Django 3.2.8 on 2021-11-11 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211111_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='extra',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
