# Generated by Django 3.2.8 on 2021-10-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20211025_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='members',
        ),
        migrations.AddField(
            model_name='chat',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Common'), (2, 'Direct')], default=1),
        ),
        migrations.DeleteModel(
            name='DirectChat',
        ),
        migrations.DeleteModel(
            name='DirectMessage',
        ),
    ]
