# Generated by Django 3.2.8 on 2021-10-26 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0011_auto_20211026_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(related_name='chats', through='chat.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
