# Generated by Django 3.2.8 on 2021-10-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_chat_members'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'chat'), name='unique_users_in_chat'),
        ),
    ]
