# Generated by Django 3.2.8 on 2021-10-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20211026_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Common'), (2, 'Direct')], default=1),
        ),
    ]
